"""remove user profile fields

Revision ID: 1fb4a8c91cfa
Revises: 596a8c94b762
Create Date: 2026-03-24 18:15:02.507670
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1fb4a8c91cfa"
down_revision = "596a8c94b762"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("t_user_profile_image_id_fkey"),
        "t_user",
        type_="foreignkey",
    )
    op.drop_column("t_user", "phone_number")
    op.drop_column("t_user", "nickname")
    op.drop_column("t_user", "profile_image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "t_user",
        sa.Column(
            "profile_image_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "t_user",
        sa.Column(
            "nickname",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "t_user",
        sa.Column(
            "phone_number",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("t_user_profile_image_id_fkey"),
        "t_user",
        "t_file",
        ["profile_image_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
