"""add organization and sis user fields

Revision ID: 596a8c94b762
Revises: 693ae09dc797
Create Date: 2026-03-24 16:33:21.004190
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "596a8c94b762"
down_revision = "693ae09dc797"
branch_labels = None
depends_on = None

HANSUNG_ORGANIZATION_ID = "11111111-1111-1111-1111-111111111111"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    organization_auth_provider = postgresql.ENUM(
        "HANSUNG_SIS",
        name="organizationauthprovider",
        create_type=False,
    )
    user_role = postgresql.ENUM(
        "STUDENT",
        "PROFESSOR",
        "ADMIN",
        name="userrole",
        create_type=False,
    )

    organization_auth_provider.create(op.get_bind(), checkfirst=True)
    user_role.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "t_organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "auth_provider",
            organization_auth_provider,
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )

    op.get_bind().execute(
        sa.text(
            """
            INSERT INTO t_organization (
                id,
                code,
                name,
                auth_provider,
                is_active,
                created_at,
                updated_at,
                version_id
            ) VALUES (
                :id,
                'univ_hansung',
                '한성대학교',
                'HANSUNG_SIS',
                true,
                NOW(),
                NOW(),
                0
            )
            """
        ),
        {"id": HANSUNG_ORGANIZATION_ID},
    )

    op.add_column(
        "t_user",
        sa.Column("organization_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "t_user",
        sa.Column("login_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "t_user",
        sa.Column(
            "role",
            user_role,
            nullable=True,
        ),
    )
    op.alter_column(
        "t_user",
        "real_name",
        new_column_name="name",
        existing_type=sa.VARCHAR(length=100),
    )
    op.alter_column(
        "t_user",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )

    op.get_bind().execute(
        sa.text(
            """
            UPDATE t_user
            SET organization_id = :organization_id,
                login_id = username,
                role = 'STUDENT'
            WHERE organization_id IS NULL
            """
        ),
        {"organization_id": HANSUNG_ORGANIZATION_ID},
    )

    op.alter_column(
        "t_user",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "t_user",
        "login_id",
        existing_type=sa.String(length=100),
        nullable=False,
    )
    op.alter_column(
        "t_user",
        "role",
        existing_type=postgresql.ENUM(
            "STUDENT",
            "PROFESSOR",
            "ADMIN",
            name="userrole",
            create_type=False,
        ),
        nullable=False,
    )
    op.drop_constraint(op.f("t_user_email_key"), "t_user", type_="unique")
    op.drop_constraint(op.f("t_user_username_key"), "t_user", type_="unique")
    op.create_unique_constraint(
        "uq_user_organization_login_id",
        "t_user",
        ["organization_id", "login_id"],
    )
    op.create_foreign_key(
        "fk_user_organization_id",
        "t_user",
        "t_organization",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("t_user", "password")
    op.drop_column("t_user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    organization_auth_provider = postgresql.ENUM(
        "HANSUNG_SIS",
        name="organizationauthprovider",
        create_type=False,
    )
    user_role = postgresql.ENUM(
        "STUDENT",
        "PROFESSOR",
        "ADMIN",
        name="userrole",
        create_type=False,
    )

    op.add_column(
        "t_user",
        sa.Column("username", sa.VARCHAR(length=50), nullable=True),
    )
    op.add_column(
        "t_user",
        sa.Column("password", sa.VARCHAR(length=255), nullable=True),
    )
    op.execute(
        sa.text(
            """
            UPDATE t_user
            SET username = login_id,
                password = '__migrated_to_sis__'
            WHERE username IS NULL
            """
        )
    )
    op.alter_column(
        "t_user",
        "username",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "t_user",
        "password",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_constraint(
        "fk_user_organization_id",
        "t_user",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_user_organization_login_id",
        "t_user",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("t_user_username_key"),
        "t_user",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("t_user_email_key"),
        "t_user",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "t_user",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "t_user",
        "name",
        new_column_name="real_name",
        existing_type=sa.VARCHAR(length=100),
    )
    op.drop_column("t_user", "role")
    op.drop_column("t_user", "login_id")
    op.drop_column("t_user", "organization_id")
    op.drop_table("t_organization")
    organization_auth_provider.drop(op.get_bind(), checkfirst=True)
    user_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
